// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/ghzmhrm/go-blockchain/internal"
	"github.com/ghzmhrm/go-blockchain/internal/service"
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeBlockchain init the blockchain application
func InitializeBlockchain() internal.BlockchainSvc {
	blockChainServices := service.NewBlockChainServices()
	return blockChainServices
}

// wire.go:

var (
	servicesSet = wire.NewSet(service.NewBlockChainServices, wire.Bind(new(internal.BlockchainSvc), new(*service.BlockChainServices)))

	allSet = wire.NewSet(
		servicesSet,
	)
)
